### ISSUE TITLE
'fullUrlIs' method has been deleted from 'Illuminate \ Http \ Request'

### ISSUE THREAD

**Issue by frknikiz** [dwightwatson/active#10]
The method under `'Illuminate \ Http \ Request'` has been deleted. Therefore, the following error occurs;

`'ErrorException' with message 'call_user_func_array() expects parameter 1 to be a valid callback, class 'Illuminate\Http\Request' does not have a method 'fullUrlIs' `

https://github.com/dwightwatson/active/blob/a633627059c2a913ff42ac6414e560996303df4b/src/Active.php#L110

**Comment by dwightwatson** [comment]
Still looks like it's there to me...

https://github.com/laravel/framework/blob/5.4/src/Illuminate/Http/Request.php#L206-L222

Can you provide some more information about your setup?

**Comment by frknikiz** [comment]
The method is not found in version 5.1 of laravel. I am getting an error because the project has a laravel version of 5.1. For this reason the compatibility of the package seems to be 5.2 and above.

[https://github.com/laravel/framework/blob/5.1/src/Illuminate/Http/Request.php](https://github.com/laravel/framework/blob/5.1/src/Illuminate/Http/Request.php)

**Comment by frknikiz** [comment]
I solved the problem by using version 2.0.4 of the package. However, developers using packages version 2.0.5 and above seem to have problems with versions of laravel 5.1 and below.

**Comment by dwightwatson** [comment]
Ah I see, looks like it was introduced in 5.2 - I will have to update the dependency constraints to fit this. Should be fine for you to stick on `2.0.4` until you update to a newer version of Laravel.
