### ISSUE TITLE
[Question]: helpers.php

### ISSUE THREAD

**Issue by joshbruce** [dwightwatson/active#11]
Hello, thanks for this one, much appreciated.

Anyhoo. I'm developing a few services and have the need/desire for two things:

1. A singleton, which I think I've figured out.

2. A helper function similar to the way `active` and `is_active` work.

Is that what's going on in the `helpers.php` file? If so, it seems like this is a convention over configuration thing? 

Because I can't find anywhere in the `active` code that registers these methods, it doesn't have a namespace, and so on. Thank you much!

**Comment by johannesschobel** [comment]
the `helpers.php` file is "autoloaded" with the `composer.json` file in the package. Take a look at the `autoload` key in this file.. This one, additionally, loads the `helpers.php` file and makes respective functions available..

**Comment by dwightwatson** [comment]
Wow sorry for not getting back to you sooner - the email notification must have gotten lost in my inbox.

1. The `Watson\Active\Active` class in which all the logic lives is instantiated in Laravel's IoC container under the key `active`. When you use the facade it is hitting the instance of Active associated with that key.

2. Like @johannesschobel mentions above - the `helpers.php` file is autoloaded by the `composer.json` file. When you run Composer for your Laravel app it looks at your dependencies as well and automatically loads their requirements as well. Our `helpers.php` file defines some of the simple helpers you would use with this package, if they are not already defined in your app.

Hope this helps - please let me know if you have any more questions.
