### ISSUE TITLE
[Sugestion] - Not active helper

### ISSUE THREAD

**Issue by drianoaz** [dwightwatson/active#13]
Is it possible create a helper for not active route? There are situations where we need to add a classes in elements when the route is not active.

Sample:

```php
<a href="#" class="{{ not_active(['route'], 'done') }}">A link</a>
```

**Comment by dwightwatson** [comment]
There is a second helper function called `is_active()` which just returns a boolean. It would be simple to wrap this up into a function so it works as you'd expect.

```php
if (! function_exists('not_active')) {
    /**
     * Get the active class if the provided path is not active.
     *
     * @param  mixed  $routes
     * @param  string  $class
     * @return string|null
     */
    function not_active($routes, $class = null)
    {
        $routes = is_array($routes) ? $routes : [$routes];

        return active()->isActive($routes) ? null : $class;
    }
}
```
I'm not sure if this is something worth bringing into the package as this is the first time it's been brought up, but happy to reconsider if there's more interest. Either way, this should get you going in the meantime.
