### ISSUE TITLE
Class Active does not exist error

### ISSUE THREAD

**Issue by yeshwanthvshenoy** [dwightwatson/active#4]
I did the composer require step and it created the Watson folder under vendor. So I went ahead and added stuff to my `config/app.php` and here is what my `config/app.php` looks like : [http://pastebin.com/qyA3LDRa](http://pastebin.com/qyA3LDRa) and the error I receive is like this : [http://pastebin.com/Es7b4nJ5](http://pastebin.com/Es7b4nJ5). @dwightwatson could you help me out?

My view is like this :

`<li class="{{ active('dashboard') }} treeview">
<a href="{{ route('dashboard') }}"><i class="fa fa-dashboard"></i><span>Dashboard</span></a>
</li>`

**Comment by dwightwatson** [comment]
You've got the wrong class in the `aliases` part of your `config/app.php` - it's meant to be `'Active' => Watson\Active\Facades\Active::class` instead. Also, I take it this is on Laravel 5.3?

**Comment by dwightwatson** [comment]
I just tried it on a fresh Laravel 5.3 project and it works fine. Something else is going on here.

**Comment by yeshwanthvshenoy** [comment]
@dwightwatson In my `aliases` part, I added this `'Active' => Watson\Active\Facades\Active::class,` and in my `providers` part, I added this `Watson\Active\Facades\Active::class,` but still I get the same error. Any idea?

**Comment by dwightwatson** [comment]
No, the provider needs to be `Watson\Active\ActiveServiceProvider::class`. In fact, you can remove the line from your `aliases` array. Are you using any sort of config caching that might be preventing it from updating?

**Comment by yeshwanthvshenoy** [comment]
@dwightwatson I must be frank that I am new to Laravel and I am not sure what caching you mean. I did do the `php artisan cache:clear` and try. I added the line you mentioned in my provider array and then removed the line from aliases array but still keep getting the error, even after a cache clear.

**Comment by dwightwatson** [comment]
That's fine. Could you try `php artiscan config:clear` and see if the error persists?

**Comment by yeshwanthvshenoy** [comment]
@dwightwatson Cool! Its working now. So cache was the culprit then! Thanks you 👍

**Comment by dwightwatson** [comment]
Awesome :smile: Generally, you're only going to want to use `php artisan config:cache` in production, it will save Laravel from having to reload the configuration on each page request. If you cache it in development it's only going to cause headaches!

**Comment by yeshwanthvshenoy** [comment]
@dwightwatson could you shed some light on how to disable this cache thingy in development?

**Comment by dwightwatson** [comment]
It's only enabled when you run `php artisan config:cache`. I suspect you ran that earlier by mistake, or as part of a tutorial or something. As soon as you run `php artisan config:clear` though it will be disabled again.

**Comment by yeshwanthvshenoy** [comment]
@dwightwatson might be the case. Thanks!
